deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Install dependencies
      run: |
        npm install --production
        # Verify express is installed
        if [ ! -d "node_modules/express" ]; then
          echo "Critical error: Express not installed!"
          exit 1
        fi

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'freelancerio-azure-app'
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6685209C9EF84057A46D4974926C36DF }}